name: Minify and Trigger Server

on:
  push:
    branches: [main]

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and Terser
        run: |
          sudo apt-get install -y nodejs npm
          npm install -g terser

      - name: Minify JS
        run: terser dcall.js -o dcall.min.js --compress --mangle

      - name: Trigger server update
        run: curl -X POST "${{ secrets.SERVER_ADDRESS }}supersecretdoorcode=${{ secrets.SERVER_SECRET }}"
