name: Minify and Trigger Server

on:
  push:
    branches: [main]

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and Terser
        run: |
          sudo apt-get install -y nodejs npm
          npm install -g terser

      - name: Minify JS with debug
        run: |
          echo "Minifying..."
          terser dcall.js --compress --mangle -o dcall.min.js
          echo "Minified file size:"
          stat --format="%s bytes" dcall.min.js
          echo "Preview of minified file:"
          head -c 200 dcall.min.js || echo "[File empty]"

      - name: Trigger server update
        run: curl -X POST "${{ secrets.SERVER_ADDRESS }}supersecretdoorcode=${{ secrets.SERVER_SECRET }}"
