name: Minify and Trigger Server

on:
  push:
    branches: [main]

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and Terser
        run: |
          sudo apt-get install -y nodejs npm
          npm install -g terser

      - name: Check original JS file size
        run: |
          echo "Original file size:"
          stat --format="%s bytes" dcall.js
          cat dcall.js

      - name: Abort if source file is empty
        run: |
          if [ ! -s dcall.js ]; then
            echo "ERROR: Source file is empty!"
            exit 1
          fi

      - name: Minify JS
        run: terser dcall.js -o dcall.min.js --compress --mangle

      - name: Trigger server update
        run: curl -X POST "${{ secrets.SERVER_ADDRESS }}supersecretdoorcode=${{ secrets.SERVER_SECRET }}"
